$(document).ready(function(){
    document.getElementById("content").innerHTML='<h2 class="sea_head">Box Jellyfish</h2><h3>What is it?</h3><div class="panel-body">Box jellyfish are cnidarian invertebrates distinguished by their cube-shaped medusae. Some species of box jellyfish produce extremely potent venom: Chironex fleckeri, Carukia barnesi and Malo kingi. Stings from these and a few other species in the class are extremely painful and can be fatal to humans. In Australia, fatalities are most often caused by the largest species of this class of jellyfish, Chironex fleckeri.  The venom causes cells to become porous enough to allow potassium leakage, causing hyperkalemia, which can lead to cardiovascular collapse and death as quickly as within 2 to 5 minutes.</div><h3>Symptoms</h3><div class="panel-body">Immediate, excruciating pain. Whip-like sting marks on the skin – redness and swelling. Also nausea, vomiting, sweating, restlessness, headache and collapse. May stop breathing and go into cardiac arrest within a few minutes of being stung.</div><h3>Treatment</h3><div class="panel-body"><p>• Domestic vinegar should be poured liberally over any adhering tentacles to inactivate thestinging cells (nematocysts) as soon as possible. Flood the area with vinegar for at least 30seconds.</p><p>• If vinegar is not available, wash the area well using sea water (not fresh water) and pick offtentacles (this is not harmful to the rescuer).</p><p>• Dial 000 for an ambulance and seek help from a lifeguard.</p><p>• Make sure patient does NOT move.</p><p>• A cold pack or ice in a sealed, dry plastic bag may help relieve pain. Take care not to getfresh water on the area as it could activate further stinging cells.</p><p>• Artificial respiration and cardiac massage (cardiopulmonary resuscitation – CPR) may be required.</p><p>• Antivenom is available, and is recommended for all but minor stings.</p></div>';
    $('#bluebottle').click(function(){
        document.getElementById("content").innerHTML='<h2 class="sea_head">Bluebottle</h2><h3>What is it?</h3><div class="panel-body">The Portuguese man o\' war, also known as the bluebottle, is a marine hydrozoan found in the Atlantic, Indian and Pacific Oceans. Its long tentacles deliver a painful sting, which is venomous and powerful enough to kill fish and even humans. Strong winds may drive them into bays or onto beaches. Often, finding a single Portuguese man o\' war is followed by finding many others in the vicinity. They can sting while beached; the discovery of a man o\' war washed up on a beach may lead to the closure of the beach.</div><h3>Symptoms</h3><div class="panel-body">The sting may be mild or not painful since the bluebottle may be too small to be seen. Symptoms include severe low back pain, generalised cramping pain, vomiting, sweating, difficulty breathing, restlessness and anxiety. Dangerously high blood pressure may develop.</div><h3>Treatment</h3><div class="panel-body"><p>• Vinegar is NOT recommended.</p><p>• Remove any tentacles with tweezers, forceps or fingers (this is not dangerous to the rescuer; you may experience a harmless prickling feeling).</p><p>• DO NOT rub the area.</p><p>• DO NOT wash off with fresh water — use sea water.</p><p>• Immerse the affected area in hot water (no hotter than the rescuer can comfortably tolerate) for 20 minutes to relieve pain.</p><p>• If pain is not relieved by heat, or hot water is not available, stings may respond to ice packs or anaesthetic creams or lotions.</p><p>• For persistent or generalised pain, or if the sting area is large or involves sensitive areas, call an ambulance and seek assistance from a lifeguard if available.</p></div>';
        return false;
    });
    $('#stonefish').click(function(){
        document.getElementById("content").innerHTML='<h2 class="sea_head">Stonefish</h2><h3>What is it?</h3><div class="panel-body">Synanceia verrucosa is a fish species known as the reef stonefish. It is a carnivorous ray-finned fish with venomous spines. It lives on reef bottoms camouflaged as a rock. It is the most venomous known fish in the world. It can be lethal to humans. This stonefish is usually brown or gray, and it may have areas of yellow, orange or red. This species reaches up to 30–40 centimeters long; a specimen of 51 centimeters has been recorded.</div><h3>Symptoms</h3><div class="panel-body">Fish stings are usually extremely painful, which can lead to irrational behaviour. The sting wound may be bleeding, bruised or swollen.</div><h3>Treatment</h3><div class="panel-body"><p>• Call an ambulance.</p><p>• Immerse the affected area in hot water to relieve pain. (Try putting an unaffected part of your body in the hot water first to make sure you are not burning yourself.）</p><p>• DO NOT apply a pressure immobilisation bandage.</p><p>• Leave any barbs or spines in place and place padding around them. They may be plugging a wound and preventing blood loss.</p><p>• If the person is unresponsive and not breathing properly, start CPR (cardiopulmonary resuscitation).</p></div>';
        return false;
    });
    $('#octopus').click(function(){
        document.getElementById("content").innerHTML='<h2 class="sea_head">Blue-ringed Octopus</h2><h3>What is it?</h3><div class="panel-body">Blue-ringed octopuses are four highly venomous species of octopus that are found in tide pools and coral reefs in the Pacific and Indian oceans, from Japan to Australia. They can be identified by their yellowish skin and characteristic blue and black rings that change color dramatically when the animal is threatened. They eat small animals, including crabs, hermit crabs, shrimp, and other crustaceans.</div><h3>Symptoms</h3><div class="panel-body">Blue ringed octopuses secrete a nerve toxin in their saliva. Their bite is usually painless, but the person bitten will feel numb around the mouth, tongue, face and neck and will feel tight in the chest and may have difficulty breathing. Respiratory failure occurs eventually which leads to death if the person is not resuscitated. Most of the time, the victim is aware, but unable to move or respond.</div><h3>Treatment</h3><div class="panel-body"><p>• Pressure immobilisation bandages should be applied, using a broad pressure bandage and splint on the affected limb.</p><p>• Stay with the person, reassure them and keep them still.</p><p>• Assisted or artificial respiration may be needed.</p><p>• Person will need transfer to hospital – prolonged artificial respiration is often required until the effects of the venom wear off.</p><p>• There is no antivenom available.</p></div>';
        return false;
    });
    $('#jellyfish').click(function(){
        document.getElementById("content").innerHTML='<h2 class="sea_head">Box Jellyfish</h2><h3>What is it?</h3><div class="panel-body">Box jellyfish are cnidarian invertebrates distinguished by their cube-shaped medusae. Some species of box jellyfish produce extremely potent venom: Chironex fleckeri, Carukia barnesi and Malo kingi. Stings from these and a few other species in the class are extremely painful and can be fatal to humans. In Australia, fatalities are most often caused by the largest species of this class of jellyfish, Chironex fleckeri.  The venom causes cells to become porous enough to allow potassium leakage, causing hyperkalemia, which can lead to cardiovascular collapse and death as quickly as within 2 to 5 minutes.</div><h3>Symptoms</h3><div class="panel-body">Immediate, excruciating pain. Whip-like sting marks on the skin – redness and swelling. Also nausea, vomiting, sweating, restlessness, headache and collapse. May stop breathing and go into cardiac arrest within a few minutes of being stung.</div><h3>Treatment</h3><div class="panel-body"><p>• Domestic vinegar should be poured liberally over any adhering tentacles to inactivate thestinging cells (nematocysts) as soon as possible. Flood the area with vinegar for at least 30seconds.</p><p>• If vinegar is not available, wash the area well using sea water (not fresh water) and pick offtentacles (this is not harmful to the rescuer).</p><p>• Dial 000 for an ambulance and seek help from a lifeguard.</p><p>• Make sure patient does NOT move.</p><p>• A cold pack or ice in a sealed, dry plastic bag may help relieve pain. Take care not to getfresh water on the area as it could activate further stinging cells.</p><p>• Artificial respiration and cardiac massage (cardiopulmonary resuscitation – CPR) may be required.</p><p>• Antivenom is available, and is recommended for all but minor stings.</p></div>';
        return false;
    });
});

/**
$(document).ready(function(){
    document.getElementById('content').innerHTML='<div class="row" style="margin-top: 3%"><div class="col-md-4"><div class="block-16"><figure><img src="images/sea_creature/jellyfish.jpeg" alt="Image placeholder" class="img-fluid"></figure></div></div><div class="panel-group col-md-8" id="accordion" role="tablist" aria-multiselectable="true"><div class="panel panel-default"><div class="panel-heading" role="tab" id="headingOne"><h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"aria-expanded="false" aria-controls="collapseOne">Box Jellyfish</a></h4></div><div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne"><div class="panel-body"><p>• Domestic vinegar should be poured liberally over any adhering tentacles to inactivate thestinging cells (nematocysts) as soon as possible. Flood the area with vinegar for at least 30seconds.</p><p>• If vinegar is not available, wash the area well using sea water (not fresh water) and pick offtentacles (this is not harmful to the rescuer).</p><p>• Dial 000 for an ambulance and seek help from a lifeguard.</p><p>• Make sure patient does NOT move.</p><p>• A cold pack or ice in a sealed, dry plastic bag may help relieve pain. Take care not to getfresh water on the area as it could activate further stinging cells.</p><p>• Artificial respiration and cardiac massage (cardiopulmonary resuscitation – CPR) may be required.</p><p>• Antivenom is available, and is recommended for all but minor stings.</p></div></div> </div></div></div>';
    $('#bluebottle').click(function(){
        document.getElementById('content').innerHTML='<div class="row"><div class="col-md-4"><div class="block-16"><figure><img src="images/sea_creature/bluebottle.jpeg" alt="Image placeholder" class="img-fluid"></figure></div></div><div class="panel-group col-md-8" id="accordion" role="tablist" aria-multiselectable="true"><div class="panel panel-default"><div class="panel-heading" role="tab" id="headingTwo"><h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Bluebottle</a></h4></div><div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo"><div class="panel-body"><p>• Vinegar is NOT recommended.</p><p>• Remove any tentacles with tweezers, forceps or fingers (this is not dangerous to the rescuer; you may experience a harmless prickling feeling).</p><p>• DO NOT rub the area.</p><p>• DO NOT wash off with fresh water — use sea water.</p><p>• Immerse the affected area in hot water (no hotter than the rescuer can comfortably tolerate) for 20 minutes to relieve pain.</p><p>• If pain is not relieved by heat, or hot water is not available, stings may respond to ice packs or anaesthetic creams or lotions.</p><p>• For persistent or generalised pain, or if the sting area is large or involves sensitive areas, call an ambulance and seek assistance from a lifeguard if available.</p></div></div></div></div></div>';
        return false;
    });
    $('#stonefish').click(function(){
        document.getElementById('content').innerHTML='<div class="row"><div class="col-md-4"><div class="block-16"><figure><img src="images/sea_creature/stonefish.jpeg" alt="Image placeholder" class="img-fluid"></figure></div></div><div class="panel-group col-md-8" id="accordion" role="tablist" aria-multiselectable="true"><div class="panel panel-default"><div class="panel-heading" role="tab" id="headingThree"><h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Stonefish</a></h4></div><div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree"><div class="panel-body"><p>• Call an ambulance.</p><p>• Immerse the affected area in hot water to relieve pain. (Try putting an unaffected part of your body in the hot water first to make sure you are not burning yourself.）</p><p>• DO NOT apply a pressure immobilisation bandage.</p><p>• Leave any barbs or spines in place and place padding around them. They may be plugging a wound and preventing blood loss.</p><p>• If the person is unresponsive and not breathing properly, start CPR (cardiopulmonary resuscitation).</p></div></div></div></div></div>';
        return false;
    });
    $('#octopus').click(function(){
        document.getElementById('content').innerHTML='<div class="row"><div class="col-md-4"><div class="block-16"><figure><img src="images/sea_creature/octopus.jpeg" alt="Image placeholder" class="img-fluid"></figure></div></div><div class="panel-group col-md-8" id="accordion" role="tablist" aria-multiselectable="true"><div class="panel panel-default"><div class="panel-heading" role="tab" id="headingFour"><h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">Blue-ringed Octopus</a></h4></div><div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour"><div class="panel-body"></p><p>• Pressure immobilisation bandages should be applied, using a broad pressure bandage and splint on the affected limb.</p><p>• Stay with the person, reassure them and keep them still.</p><p>• Assisted or artificial respiration may be needed.</p><p>• Person will need transfer to hospital – prolonged artificial respiration is often required until the effects of the venom wear off.</p><p>• There is no antivenom available.</p></div></div></div></div></div>';
        return false;
    });
    $('#seasnail').click(function(){
        document.getElementById('content').innerHTML='<div class="row"><div class="col-md-4"><div class="block-16"><figure><img src="images/sea_creature/snail.jpeg" alt="Image placeholder" class="img-fluid"> </figure></div></div><div class="panel-group col-md-8" id="accordion" role="tablist" aria-multiselectable="true"><div class="panel panel-default"><div class="panel-heading" role="tab" id="headingFive"><h4 class="panel-title"><a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive"aria-expanded="false" aria-controls="collapseFive">Sea Snail</a></h4></div><div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive"><div class="panel-body"></p><p>• Call 000 for an ambulance.</p><p>• Pressure immobilisation, using a broad pressure bandage and splint, is recommended.</p><p>• Stay with the person, reassure them and keep them still.</p><p>• Prolonged artificial respiration, even mechanical ventilation, may be required.</p><p>• At this stage, there is no antivenom available for cone shell stings.</p><p>• A tetanus injection may also be needed in case the wound is contaminated.</p></div></div></div></div></div>';
        return false;
    });
});
*/